### ISSUE TITLE
error with newer kubectl version about extensions/v1beta1

### ISSUE THREAD

**Issue by ykoehler** [SeldonIO/k8s-local-docker-registry#1]
service/docker-private-registry unchanged
unable to recognize no matches for kind "Deployment" in version "extensions/v1beta1"

**Comment by saeid93** [comment]
I'm facing the same issue, did you find any solution for this?

**Comment by arLevi** [comment]
I've adjusted it to 
```
- apiVersion: apps/v1
  kind: Deployment 
``` 

Also replaced Ingress's code to:
```
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: docker-private-registry-ingress
spec:
  rules:
    - host: docker-private-registry.default.svc.cluster.local
      http:
        paths:
        - path: /
          pathType: Prefix
          backend:
            service:
              name: docker-private-registry
              port:
                number: 5000
```
